(()=>{'use strict';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const css=`
.rm-news-slider{position:relative;min-height:360px;border:1px solid #34363b;border-radius:10px;overflow:hidden;background:#111;color:#fff;box-shadow:0 18px 40px rgba(0,0,0,.28)}
.rm-news-slide{position:absolute;inset:0;opacity:0;visibility:hidden;transition:opacity .45s ease;display:flex;align-items:flex-end;background:#161719 center/cover no-repeat}
.rm-news-slide.is-active{opacity:1;visibility:visible}
.rm-news-slide:before{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(0,0,0,.88) 0%,rgba(0,0,0,.64) 45%,rgba(0,0,0,.15) 100%),linear-gradient(0deg,rgba(0,0,0,.9),transparent 55%)}
.rm-news-copy{position:relative;z-index:2;width:min(680px,88%);padding:30px}.rm-news-copy .rm-cat{display:inline-flex;background:#d71920;color:#fff;padding:6px 9px;font:900 9px Montserrat;border-radius:3px;text-transform:uppercase}.rm-news-copy h1{font:900 clamp(25px,3.2vw,42px)/1.04 Montserrat;margin:10px 0 9px;letter-spacing:-.7px}.rm-news-copy p{font:500 12px/1.55 Roboto;color:#e9e9e9;margin:0;max-width:590px}.rm-news-copy a{display:inline-flex;margin-top:16px;background:#f7d51b;color:#111;padding:10px 14px;border-radius:4px;text-decoration:none;font:900 9px Montserrat}.rm-news-nav{position:absolute;z-index:5;right:16px;bottom:18px;display:flex;align-items:center;gap:7px}.rm-news-nav button{width:34px;height:34px;border:1px solid rgba(255,255,255,.5);background:rgba(0,0,0,.5);color:#fff;border-radius:50%;cursor:pointer;font-size:16px}.rm-news-dots{display:flex;gap:5px;margin:0 4px}.rm-news-dot{width:6px;height:6px;border:0;border-radius:50%;padding:0;background:#aaa;cursor:pointer}.rm-news-dot.is-active{background:#f7d51b;transform:scale(1.35)}
.ciwara-hero .hero-copy.ciwara-hero-video-col{min-width:0}.ciwara-hero .hero-grid{align-items:stretch;padding:18px 0}.ciwara-hero .hero-player{align-self:center}.ciwara-hero .hero-bg{opacity:.65}
@media(max-width:900px){.rm-news-slider{min-height:320px}.rm-news-copy{padding:22px}.ciwara-hero .hero-grid{padding:18px 0 25px}.rm-news-nav{right:12px;bottom:12px}}
@media(max-width:650px){.rm-news-slider{min-height:290px;border-radius:8px}.rm-news-copy{padding:18px}.rm-news-copy h1{font-size:24px}.rm-news-copy p{font-size:11px}.rm-news-copy a{margin-top:12px}.rm-news-nav button{width:30px;height:30px}}
`;
function addCss(){if(document.getElementById('refonte-home-final-css'))return;const s=document.createElement('style');s.id='refonte-home-final-css';s.textContent=css;document.head.appendChild(s)}
async function getNews(){try{const r=await fetch('data/actualites-slider.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();return(d.items||[]).filter(x=>x.active!==false).sort((a,b)=>(Number(a.order)||999)-(Number(b.order)||999))}catch(e){return[]}}
function mount(items){const host=document.querySelector('.ciwara-hero-video-col');if(!host||!items.length)return;const slider=document.createElement('div');slider.className='rm-news-slider';slider.setAttribute('aria-label','Grand slider des actualités Ciwara');slider.innerHTML=items.map((x,i)=>`<article class="rm-news-slide ${i===0?'is-active':''}" style="background-image:url('${esc(x.image||'logo.jpg')}')"><div class="rm-news-copy"><span class="rm-cat">${esc(x.category||'Actualité')}</span><h1>${esc(x.title||'Actualité Ciwara')}</h1><p>${esc(x.description||'Retrouvez les informations de Ciwara Infos.')}</p><a href="${esc(x.link||'ciwara-info.html')}" ${/^https?:/i.test(x.link||'')?'target="_blank" rel="noopener"':''}>LIRE L’ARTICLE →</a></div></article>`).join('')+`<div class="rm-news-nav"><button type="button" class="rm-prev" aria-label="Actualité précédente">‹</button><div class="rm-news-dots">${items.map((_,i)=>`<button type="button" class="rm-news-dot ${i===0?'is-active':''}" data-index="${i}" aria-label="Actualité ${i+1}"></button>`).join('')}</div><button type="button" class="rm-next" aria-label="Actualité suivante">›</button></div>`;host.innerHTML='';host.appendChild(slider);let index=0,timer=null;const slides=[...slider.querySelectorAll('.rm-news-slide')],dots=[...slider.querySelectorAll('.rm-news-dot')];const show=n=>{index=(n+slides.length)%slides.length;slides.forEach((s,i)=>s.classList.toggle('is-active',i===index));dots.forEach((d,i)=>d.classList.toggle('is-active',i===index))};const restart=()=>{clearInterval(timer);timer=setInterval(()=>show(index+1),6500)};slider.querySelector('.rm-prev').onclick=()=>{show(index-1);restart()};slider.querySelector('.rm-next').onclick=()=>{show(index+1);restart()};dots.forEach(d=>d.onclick=()=>{show(Number(d.dataset.index));restart()});slider.addEventListener('mouseenter',()=>clearInterval(timer));slider.addEventListener('mouseleave',restart);restart()}
function addHeaderSocials(){const nav=document.querySelector('.portal-nav .container');const links=document.querySelector('.portal-links');if(!nav||!links||nav.querySelector('.rm-socials'))return;const box=document.createElement('div');box.className='rm-socials';box.innerHTML='<a href="https://www.facebook.com/radiociwarafm/" target="_blank" rel="noopener" aria-label="Facebook">f</a><a href="https://www.youtube.com/" target="_blank" rel="noopener" aria-label="YouTube">▶</a>';nav.insertBefore(box,document.querySelector('.menu-toggle'))}
function boot(){addCss();addHeaderSocials();getNews().then(mount)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
