(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c])),img=u=>u||'logo.jpg';
let audio=$('radioPlayer');if(!audio){audio=document.createElement('audio');audio.id='radioPlayer';audio.preload='none';audio.setAttribute('playsinline','');document.body.appendChild(audio)}
const buttons=[...document.querySelectorAll('[data-play]')],statusEls=[$('status'),$('playerStatus')].filter(Boolean),sources=['https://ciwarafm.radiostream321.com/stream','https://ciwarafm.radiostream321.com/','http://ciwarafm.radiostream321.com/stream'];let si=0;
const status=t=>statusEls.forEach(e=>e.textContent=t),sync=()=>{const p=!audio.paused&&!audio.ended;buttons.forEach(b=>b.textContent=b.id==='barPlay'?(p?'Ⅱ':'▶'):(p?'Ⅱ ARRÊTER':'▶ ÉCOUTER EN DIRECT'));buttons.forEach(b=>b.classList.toggle('playing',p))};
const setSource=()=>{audio.src=sources[si];audio.load()};
async function playRadio(){status('🔴 Connexion à Radio Ciwara…');try{await audio.play();status('🔴 Radio Ciwara — EN DIRECT')}catch(e){if(si<sources.length-1){si++;setSource();try{await audio.play();status('🔴 Radio Ciwara — EN DIRECT')}catch(_){status('Le flux direct est indisponible pour le moment.')}}else status('Le flux direct est indisponible pour le moment.')}sync()}
buttons.forEach(b=>b.addEventListener('click',()=>audio.paused||audio.ended?playRadio():(audio.pause(),status('Radio en pause'))));audio.addEventListener('playing',()=>{status('🔴 Radio Ciwara — EN DIRECT');sync()});audio.addEventListener('pause',sync);audio.addEventListener('error',()=>{if(si<sources.length-1){si++;setSource();audio.play().catch(()=>status('Flux indisponible'))}else status('Le flux direct est indisponible pour le moment.');sync()});
const menu=$('mainNav'),toggle=$('menuToggle');if(toggle&&menu)toggle.onclick=()=>menu.classList.toggle('open');if(menu)menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>menu.classList.remove('open')));
const ticker=$('breakingItems'),tickerBtn=$('tickerToggle');let paused=false;if(tickerBtn&&ticker)tickerBtn.onclick=()=>{paused=!paused;ticker.style.animationPlayState=paused?'paused':'running';tickerBtn.textContent=paused?'▶':'Ⅱ'};
async function get(path){const r=await fetch(path+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(path);return r.json()}
function renderNews(items){const grid=$('newsGrid');if(!grid)return;items=items.filter(x=>x.published!==false);grid.innerHTML=items.length?items.slice(0,13).map(x=>`<article class="news-card"><div class="news-image"><img src="${esc(img(x.image))}" alt="${esc(x.title||'')}" loading="lazy" onerror="this.onerror=null;this.src='logo.jpg'"></div><div class="news-content"><span class="news-source">${esc(x.category||x.source||'CIWARA INFOS')}</span><h3>${esc(x.title||'Actualité')}</h3><p>${esc(x.description||'')}</p><div class="news-meta">${esc(x.date||'')} · ${esc(x.source||'Ciwara Infos')}</div><p style="margin-top:10px"><a href="${esc(x.link||'ciwara-info.html')}">Lire l'article →</a></p></div></article>`).join(''):'<div class="empty-note">Les actualités sont temporairement indisponibles.</div>'}
function ensureStyle(){if($('cms-home-style'))return;const s=document.createElement('style');s.id='cms-home-style';s.textContent=`.cms-hero-managed{position:relative;overflow:hidden;border-radius:10px;min-height:360px;background:#111;color:#fff;display:flex;align-items:end}.cms-hero-managed img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;opacity:.72}.cms-hero-managed:after{content:'';position:absolute;inset:35% 0 0;background:linear-gradient(transparent,rgba(0,0,0,.92))}.cms-hero-copy{position:relative;z-index:2;padding:28px;max-width:760px}.cms-hero-copy .eyebrow{color:#f7d51b;font:900 10px Montserrat}.cms-hero-copy h1{font:900 38px/1.05 Montserrat;margin:8px 0}.cms-hero-copy p{font:500 14px/1.55 Roboto;color:#eee}.cms-hero-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px}.cms-hero-actions a{padding:11px 14px;border-radius:7px;background:#d71920;color:#fff;text-decoration:none;font:900 9px Montserrat}.cms-hero-actions a.secondary{background:#fff;color:#111}.cms-world-slider{margin:20px 0;background:#111;color:#fff;border-radius:9px;overflow:hidden}.cms-world-head{padding:13px 16px;border-bottom:1px solid #333;display:flex;justify-content:space-between;gap:10px;align-items:center}.cms-world-head b{font:900 14px Montserrat}.cms-world-head span{color:#f7d51b;font:900 9px Montserrat}.cms-world-track{display:flex;gap:12px;overflow:auto;padding:12px}.cms-world-card{position:relative;flex:0 0 260px;height:155px;border-radius:7px;overflow:hidden;color:#fff;text-decoration:none;background:#222}.cms-world-card img{width:100%;height:100%;object-fit:cover}.cms-world-card:after{content:'';position:absolute;inset:40% 0 0;background:linear-gradient(transparent,rgba(0,0,0,.95))}.cms-world-card strong{position:absolute;z-index:2;left:11px;right:11px;bottom:11px;font:800 12px/1.2 Montserrat}.cms-side-managed{display:flex;flex-direction:column;gap:15px}.cms-side-item{padding:12px 0;border-top:1px solid #eee}.cms-side-item:first-child{border-top:0}.cms-side-item img{width:100%;height:100px;object-fit:cover;border-radius:5px;margin-bottom:7px}.cms-side-item a{color:#333;text-decoration:none}.cms-side-item b{display:block;font:800 12px/1.3 Montserrat}.cms-side-item small{display:block;color:#777;margin-top:4px}.cms-facebook{background:#111;color:#fff;border-radius:7px;overflow:hidden}.cms-facebook-head{padding:12px 14px;background:#1877f2;font:900 11px Montserrat}.cms-facebook-body{padding:12px}.cms-facebook iframe{width:100%;border:0;min-height:260px}.cms-facebook a{color:#fff}.cms-facebook-placeholder{padding:20px;background:#202124;color:#ccc;font-size:11px}@media(max-width:700px){.cms-hero-managed{min-height:300px}.cms-hero-copy h1{font-size:27px}.cms-world-card{flex-basis:230px}}`;document.head.appendChild(s)}
function renderHero(h){/* Le Hero original reste intact : aucun remplacement du DOM, donc Caster.fm et le slider ne sont plus détruits. */}
function renderWorldSlider(d){if(!d||d.enabled===false)return;const items=(d.items||[]).filter(x=>x.active!==false).sort((a,b)=>(Number(a.order)||9999)-(Number(b.order)||9999));if(!items.length)return;let box=document.querySelector('.cms-world-slider');if(!box){box=document.createElement('section');box.className='cms-world-slider';const hero=document.querySelector('.ciwara-hero');(hero?hero.parentElement:document.querySelector('.portal-main'))?.insertAdjacentElement('afterend',box)}if(!box)return;box.innerHTML=`<div class="cms-world-head"><b>${esc(d.title||'Actualité du Mali et du monde')}</b><span>CIWARA INFOS</span></div><div class="cms-world-track">${items.map(x=>`<a class="cms-world-card" href="${esc(x.link||'ciwara-info.html')}">${x.image?`<img src="${esc(x.image)}" alt="${esc(x.title||'')}" loading="lazy">`:''}<strong>${esc(x.title||'Actualité')}</strong></a>`).join('')}</div>`}
function renderSidebar(d,facebook){const side=document.querySelector('.portal-sidebar');if(!side)return;let host=side.querySelector('.cms-side-managed');if(d&&d.enabled!==false){if(!host){host=document.createElement('div');host.className='side-box cms-side-managed';side.prepend(host)}host.innerHTML=`<div class="side-title">${esc(d.title||'À ne pas manquer')}</div><div class="side-list">${(d.items||[]).filter(x=>x.active!==false).sort((a,b)=>(Number(a.order)||9999)-(Number(b.order)||9999)).map(x=>`<div class="cms-side-item">${x.image?`<img src="${esc(x.image)}" alt="" loading="lazy">`:''}<a href="${esc(x.link||'#')}"><b>${esc(x.title||'Élément')}</b>${x.text?`<small>${esc(x.text)}</small>`:''}</a></div>`).join('')}</div>`}if(facebook&&facebook.enabled){let fb=side.querySelector('.cms-facebook');if(!fb){fb=document.createElement('div');fb.className='side-box cms-facebook';side.appendChild(fb)}const src=facebook.embedUrl||facebook.url;fb.innerHTML=`<div class="cms-facebook-head">${esc(facebook.title||'Facebook Live')}</div><div class="cms-facebook-body">${src?`<iframe src="${esc(src)}" height="${Number(facebook.height)||420}" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share" allowfullscreen></iframe>`:`<div class="cms-facebook-placeholder">Aucun lecteur Facebook configuré. Ajoute le lien ou le code d'intégration depuis le CMS.</div>`}</div>`}else side.querySelector('.cms-facebook')?.remove()}
async function loadNews(){try{const d=await get('data/news.json'),e=await get('data/ciwara-11-sept-2026.json').catch(()=>({items:[]})),all=[...(e.items||[]),...(d.items||[])];renderNews(all);if(ticker&&all.length)ticker.innerHTML=all.slice(0,8).map(x=>`<span>${esc(x.title)} <small>— ${esc(x.category||x.source||'Ciwara Infos')}</small></span>`).join('')}catch(e){renderNews([])}}
function ensureCaster(){const e=document.querySelector('.ciwara-caster-card .cstrEmbed');if(!e)return;if([...document.scripts].some(s=>s.src.includes('cdn.cloud.caster.fm/widgets/embed.js')))return;const s=document.createElement('script');s.src='https://cdn.cloud.caster.fm/widgets/embed.js';s.async=true;document.body.appendChild(s)}
function updateBase(settings,seo){if(settings){document.querySelectorAll('.ciwara-caster-card .player-title b').forEach(e=>e.textContent='ÉCOUTER '+(settings.station||'RADIO CIWARA 105.5 FM'));document.querySelectorAll('.media-box.radio small').forEach(e=>e.textContent=(settings.frequency||'105.5 FM')+' · Bamako · 24h/24')}if(seo){document.title=seo.title||document.title;const d=document.querySelector('meta[name="description"]');if(d&&seo.description)d.content=seo.description;const c=document.querySelector('link[rel="canonical"]');if(c&&seo.canonical)c.href=seo.canonical}}
function renderPrograms(items){const box=document.querySelector('#programmes .schedule');if(box&&items.length)box.innerHTML=items.filter(x=>x.active!==false).map(x=>`<div><time>${esc(x.schedule||'')}</time><b>${esc(x.name||'Programme')}</b><small>${esc(x.description||x.host||'')}</small></div>`).join('')}
function renderPodcasts(items){const box=document.querySelector('#podcasts .podcast-list');if(box&&items.length)box.innerHTML=items.filter(x=>x.active!==false).map((x,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><div>${x.image?`<img class="cms-thumb" src="${esc(x.image)}" alt="" loading="lazy">`:''}<small>Podcast Ciwara</small><b>${esc(x.title||'Podcast')}</b><em>${esc(x.description||'Réécouter')}</em>${x.audio?`<audio controls preload="none" src="${esc(x.audio)}" style="width:100%;margin-top:7px"></audio>`:''}</div></article>`).join('')}
function renderAds(items){const grid=document.querySelector('.portal-ad-grid');if(!grid)return;const a=items.filter(x=>x.active!==false&&x.image).slice(0,3);if(a.length)grid.innerHTML=a.map(x=>`<a class="portal-ad cms-ad" href="${esc(x.link||'#contact')}"><img src="${esc(x.image)}" alt="${esc(x.title||'Publicité')}" loading="lazy"></a>`).join('')}
function renderPartners(items){const footer=[...document.querySelectorAll('footer .footer-grid>div')].find(x=>/PARTENAIRES/i.test(x.textContent||''));if(!footer||!items.length)return;let box=footer.querySelector('.cms-partners');if(!box){box=document.createElement('div');box.className='cms-partners';footer.appendChild(box)}box.innerHTML=items.filter(x=>x.active!==false).map(x=>`<a class="cms-partner" href="${esc(x.link||'#')}" target="_blank" rel="noopener"><img src="${esc(img(x.logo))}" alt="${esc(x.name||'Partenaire')}"><span>${esc(x.name||'Partenaire')}</span></a>`).join('')}
async function loadCms(){try{const [settings,accueil,seo,programmes,podcasts,ads,partners,hero,world,side,fb]=await Promise.all([get('data/site-settings.json'),get('data/accueil.json'),get('data/seo.json'),get('data/programmes.json'),get('data/podcasts.json'),get('data/publicites.json'),get('data/partenaires.json'),get('data/hero.json'),get('data/actualites-slider.json'),get('data/sidebar.json'),get('data/facebook-live.json')]);ensureStyle();updateBase(settings,seo);renderHero(hero);renderWorldSlider(world);renderSidebar(side,fb);renderPrograms(programmes.items||[]);renderPodcasts(podcasts.items||[]);renderAds(ads.items||[]);renderPartners(partners.items||[]);if(accueil.alert&&ticker)ticker.innerHTML='<span>'+esc(accueil.alert)+'</span>'}catch(e){console.warn('CMS data non disponible',e)}}
function registerPWA(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
const y=$('year');if(y)y.textContent=new Date().getFullYear();setSource();sync();ensureCaster();loadNews();loadCms();registerPWA();
})();