(()=>{
'use strict';
const $=id=>document.getElementById(id),buttons=[...document.querySelectorAll('[data-play]')];
let audio=$('radioPlayer');if(!audio){audio=document.createElement('audio');audio.id='radioPlayer';audio.preload='none';audio.setAttribute('playsinline','');document.body.appendChild(audio)}
const statusEls=[$('status'),$('playerStatus')].filter(Boolean),sources=['https://ciwarafm.radiostream321.com/stream','https://ciwarafm.radiostream321.com/','http://ciwarafm.radiostream321.com/'];let sourceIndex=0;
const status=t=>statusEls.forEach(e=>e.textContent=t),sync=()=>{const p=!audio.paused&&!audio.ended;buttons.forEach(b=>{b.classList.toggle('playing',p);b.textContent=b.id==='barPlay'?(p?'Ⅱ':'▶'):(p?'Ⅱ ARRÊTER':'▶ ÉCOUTER EN DIRECT')})};
const setSource=()=>{audio.src=sources[sourceIndex];audio.load()};
async function playRadio(){status('🔴 Connexion à Radio Ciwara…');if(!audio.src)setSource();try{await audio.play();status('🔴 Radio Ciwara — EN DIRECT')}catch(e){if(sourceIndex<sources.length-1){sourceIndex++;setSource();try{await audio.play();status('🔴 Radio Ciwara — EN DIRECT')}catch(_){status('Le flux direct est indisponible pour le moment.')}}else status('Le flux direct est indisponible pour le moment.')}sync()}
buttons.forEach(b=>b.addEventListener('click',()=>{if(!audio.paused&&!audio.ended){audio.pause();status('Radio en pause')}else playRadio()}));audio.addEventListener('playing',()=>{status('🔴 Radio Ciwara — EN DIRECT');sync()});audio.addEventListener('pause',sync);audio.addEventListener('error',()=>{if(sourceIndex<sources.length-1){sourceIndex++;setSource();audio.play().catch(()=>status('Flux indisponible'))}else status('Le flux direct est indisponible pour le moment.');sync()});
const menu=$('mainNav'),menuToggle=$('menuToggle');if(menuToggle&&menu)menuToggle.onclick=()=>menu.classList.toggle('open');if(menu)menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>menu.classList.remove('open')));
const ticker=$('breakingItems'),tickerBtn=$('tickerToggle');let paused=false;if(tickerBtn&&ticker)tickerBtn.onclick=()=>{paused=!paused;ticker.style.animationPlayState=paused?'paused':'running';tickerBtn.textContent=paused?'▶':'Ⅱ'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const imageSrc=u=>{if(!u)return'logo.jpg';if(/^https?:\/\//i.test(u)||/^data:/i.test(u))return u;return u.replace(/^\.\//,'')};
function renderNews(items){const grid=$('newsGrid');if(!grid)return;if(!items.length){grid.innerHTML='<div class="empty-note">Les actualités sont temporairement indisponibles.</div>';return}grid.innerHTML=items.slice(0,8).map(x=>`<article class="news-card"><div class="news-image"><img src="${esc(imageSrc(x.image))}" alt="${esc(x.title||'')}" loading="lazy" onerror="this.onerror=null;this.src='logo.jpg'"></div><div class="news-content"><span class="news-source">${esc(x.source||'CIWARA INFOS')}</span><h3>${esc(x.title||'Actualité')}</h3><p>${esc(x.description||'')}</p><div class="news-meta">${esc(x.date||'')} · ${esc(x.source||'Ciwara Infos')}</div><p style="margin-top:10px"><a href="${esc(x.link||'ciwara-info.html')}">Lire l'article →</a></p></div></article>`).join('')}
function slider(items){const target=document.querySelector('.portal-main .section-title');if(!target||!items.length)return;let w=document.querySelector('.ciwara-home-slider');if(!w){w=document.createElement('section');w.className='ciwara-home-slider';target.insertAdjacentElement('afterend',w)}const list=items.filter(x=>x.image).slice(0,12);w.innerHTML='<div class="cih-head"><b>CIWARA INFOS N°514</b><span>11 SEPTEMBRE 2026</span></div><div class="cih-track">'+list.map(x=>`<a href="${esc(x.link||'ciwara-info.html')}" class="cih-card"><img src="${esc(imageSrc(x.image))}" alt="${esc(x.title||'')}" onerror="this.src='logo.jpg'"><strong>${esc(x.title||'')}</strong></a>`).join('')+'</div>'};
async function loadNews(){try{const r=await fetch('data/news.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('news');const d=await r.json(),items=Array.isArray(d.items)?d.items:[];renderNews(items);slider(items);if(ticker&&items.length)ticker.innerHTML=items.slice(0,8).map(x=>`<span>${esc(x.title)} <small>— ${esc(x.source||'')}</small></span>`).join('')}catch(e){console.error(e);renderNews([])}}
function ensureCaster(){const e=document.querySelector('.ciwara-caster-card .cstrEmbed');if(!e)return;if([...document.scripts].some(s=>s.src.includes('cdn.cloud.caster.fm/widgets/embed.js')))return;const s=document.createElement('script');s.src='https://cdn.cloud.caster.fm/widgets/embed.js';s.async=true;document.body.appendChild(s)}
const style=document.createElement('style');style.textContent='.ciwara-home-slider{margin:0 0 20px;background:#111;color:#fff;border-radius:9px;overflow:hidden}.cih-head{display:flex;justify-content:space-between;padding:12px 15px;border-bottom:1px solid #333;font:900 10px Montserrat}.cih-head span{color:#f7d51b}.cih-track{display:flex;gap:12px;overflow:auto;padding:12px}.cih-card{position:relative;flex:0 0 250px;height:145px;border-radius:7px;overflow:hidden;color:#fff;text-decoration:none;background:#222}.cih-card img{width:100%;height:100%;object-fit:cover}.cih-card:after{content:"";position:absolute;inset:45% 0 0;background:linear-gradient(transparent,rgba(0,0,0,.9))}.cih-card strong{position:absolute;z-index:2;left:10px;right:10px;bottom:10px;font:800 12px/1.2 Montserrat}.cih-track::-webkit-scrollbar{height:5px}.cih-track::-webkit-scrollbar-thumb{background:#d71920}';document.head.appendChild(style);
const y=$('year');if(y)y.textContent=new Date().getFullYear();setSource();sync();ensureCaster();loadNews();
})();
