(()=>{'use strict';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const css=()=>{if(document.getElementById('site-builder-style'))return;const s=document.createElement('style');s.id='site-builder-style';s.textContent=`#cmsBuilder{width:100%;max-width:1180px;margin:0 auto;padding:0 16px 30px;box-sizing:border-box}.cms-custom-block{margin:18px 0;background:#fff;border:1px solid #ddd;border-radius:var(--cms-radius,10px);overflow:hidden}.cms-custom-block .cms-block-head{padding:14px 18px;border-top:4px solid var(--cms-primary,#0b8f4d);display:flex;justify-content:space-between;align-items:center;gap:12px}.cms-custom-block .cms-block-head h2{margin:0;font:900 20px Montserrat}.cms-custom-block .cms-block-body{padding:18px}.cms-custom-block img{max-width:100%;display:block;border-radius:8px}.cms-custom-block video,.cms-custom-block iframe{width:100%;min-height:300px;border:0;border-radius:8px}.cms-custom-block audio{width:100%}.cms-custom-columns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.cms-custom-card{border:1px solid #ddd;border-radius:8px;padding:14px}.cms-custom-button{display:inline-block;padding:10px 14px;border-radius:7px;background:var(--cms-accent,#d71920);color:#fff;text-decoration:none;font:900 10px Montserrat}.cms-custom-muted{color:#777;font:500 11px Roboto}@media(max-width:700px){#cmsBuilder{padding:0 10px 25px}.cms-custom-columns{grid-template-columns:1fr}.cms-custom-block video,.cms-custom-block iframe{min-height:220px}}`;document.head.appendChild(s)};
const applyTheme=t=>{if(!t)return;const r=document.documentElement.style;r.setProperty('--cms-primary',t.primary||'#0b8f4d');r.setProperty('--cms-secondary',t.secondary||'#f7d51b');r.setProperty('--cms-accent',t.accent||'#d71920');r.setProperty('--cms-text',t.text||'#111214');r.setProperty('--cms-background',t.background||'#f1f1ef');r.setProperty('--cms-radius',(Number(t.radius)||10)+'px');if(t.background)document.body.style.background=t.background;const root=document.querySelector('.container');if(root&&t.maxWidth)root.style.maxWidth=(Number(t.maxWidth)||1180)+'px'};
const find=(sel)=>{try{return document.querySelector(sel)}catch(_){return null}};
function customHTML(b){const s=b.settings||{};let body='';switch(b.type){case'text':body=`<div class="cms-block-body"><div>${s.html||esc(s.text||'')}</div></div>`;break;case'image':body=`<div class="cms-block-body">${s.image?`<img src="${esc(s.image)}" alt="${esc(s.alt||s.title||'')}">`:''}${s.caption?`<p class="cms-custom-muted">${esc(s.caption)}</p>`:''}</div>`;break;case'banner':body=`<div class="cms-block-body" style="text-align:center">${s.image?`<img src="${esc(s.image)}" alt="${esc(s.alt||'')}">`:''}${s.link?`<p><a class="cms-custom-button" href="${esc(s.link)}">${esc(s.button||'En savoir plus')}</a></p>`:''}</div>`;break;case'video':body=`<div class="cms-block-body">${s.url?`<iframe src="${esc(s.url)}" loading="lazy" allowfullscreen title="${esc(s.title||'Vidéo')}"></iframe>`:''}</div>`;break;case'audio':body=`<div class="cms-block-body">${s.url?`<audio controls preload="none" src="${esc(s.url)}"></audio>`:''}</div>`;break;case'html':body=`<div class="cms-block-body">${s.html||''}</div>`;break;case'spacer':body=`<div class="cms-block-body" style="height:${Math.max(10,Number(s.height)||40)}px;padding:0"></div>`;break;case'columns':body=`<div class="cms-block-body"><div class="cms-custom-columns">${(s.items||[]).map(x=>`<div class="cms-custom-card"><h3>${esc(x.title||'')}</h3><div>${x.html||esc(x.text||'')}</div></div>`).join('')}</div></div>`;break;default:body=`<div class="cms-block-body">${s.html||esc(s.text||'')}</div>`}return `<section class="cms-custom-block" data-builder-id="${esc(b.id)}"><div class="cms-block-head"><h2>${esc(b.label||s.title||'Section')}</h2>${s.kicker?`<span class="cms-custom-muted">${esc(s.kicker)}</span>`:''}</div>${body}</section>`}
function renderBlocks(cfg){css();applyTheme(cfg.theme);let zone=document.getElementById('cmsBuilder');if(!zone){zone=document.createElement('div');zone.id='cmsBuilder';const main=document.querySelector('main')||document.body;const anchor=document.querySelector('.canal-plus-block')||document.querySelector('.ciwara-caster-card')||main.lastElementChild;main.insertBefore(zone,anchor||null)}zone.innerHTML='';const page=cfg.pages&&cfg.pages.home;if(!page)return;const blocks=(page.blocks||[]).filter(b=>b.enabled!==false).sort((a,b)=>(Number(a.order)||9999)-(Number(b.order)||9999));for(const b of blocks){if(b.type==='custom-zone')continue;if(b.type==='facebook-live')continue;if(b.type==='existing'){const el=find(b.target);if(el){el.dataset.builderId=b.id;el.dataset.builderLabel=b.label||'';el.classList.toggle('cms-builder-disabled',b.enabled===false);if(b.settings&&b.settings.title){const h=el.querySelector('.section-title h2,.side-title,h2');if(h)h.textContent=b.settings.title}if(b.settings&&b.settings.text){const n=el.querySelector('p,span');if(n)n.textContent=b.settings.text}}continue}zone.insertAdjacentHTML('beforeend',customHTML(b))}}
async function boot(){try{const r=await fetch('data/site-builder.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)return;const cfg=await r.json();renderBlocks(cfg)}catch(e){console.warn('Site Builder:',e)}}
window.CiwaraSiteBuilder={render:renderBlocks};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
