const CACHE='ciwara-v20260913';
const CORE=['./','./index.html','./style.css?v=20260902','./script.js?v=20260902','./refonte-maquette.css?v=20260913','./refonte-dynamique.css?v=20260913','./refonte-dynamique.js?v=20260913','./manifest.webmanifest','./favicon-ciwara.svg','./logo.jpg','./logo%20hitradio.png','./data/news.json','./data/ciwara-info.json','./ciwara-info.html','./ciwara-tv.html','./download-app.html'];
const DATA_PREFIX='/data/';
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(CORE)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});
async function enhanceHtml(response){if(!response||!response.ok)return response;try{const text=await response.text();if(text.includes('refonte-dynamique.js'))return new Response(text,{status:response.status,statusText:response.statusText,headers:response.headers});const enhanced=text.replace(/<\/body>/i,'<script src="./refonte-dynamique.js?v=20260913" defer></script></body>');const headers=new Headers(response.headers);headers.set('content-type','text/html; charset=UTF-8');headers.delete('content-length');return new Response(enhanced,{status:response.status,statusText:response.statusText,headers})}catch(e){return response}}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;
if(url.pathname.startsWith(DATA_PREFIX)){event.respondWith(fetch(request).then(response=>{if(response.ok){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(request,copy))}return response}).catch(()=>caches.match(request)));return}
if(request.mode==='navigate'){event.respondWith(fetch(request).then(async response=>{const enhanced=await enhanceHtml(response);const copy=enhanced.clone();caches.open(CACHE).then(cache=>cache.put(request,copy));return enhanced}).catch(()=>caches.match('./index.html')));return}
event.respondWith(caches.match(request).then(cached=>cached||fetch(request).then(response=>{if(response.ok){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(request,copy))}return response})))
});
