const CACHE='ciwara-v20260917';
const SAFE_RUNTIME='./refonte-dynamique-safe.js?v=20260917';
const EMISSIONS_RUNTIME='./refonte-emissions.js?v=20260913';
const CORE=['./','./index.html','./style.css?v=20260902','./script.js?v=20260902','./refonte-maquette.css?v=20260913','./refonte-premium.css?v=20260913','./refonte-total-v2.css?v=20260913','./refonte-rfm-layout.css?v=20260915','./refonte-cms-portal.css?v=20260915','./refonte-cms-portal.js?v=20260915','./refonte-ux-v4.css?v=20260916','./refonte-ux-v4.js?v=20260916','./refonte-dynamique.css?v=20260913',SAFE_RUNTIME,'./refonte-total-v2.js?v=20260916',EMISSIONS_RUNTIME,'./refonte-structure-v3.css?v=20260914','./manifest.webmanifest','./favicon-ciwara.svg','./logo.jpg','./logo%20hitradio.png','./data/news.json','./data/ciwara-info.json','./data/programmes.json','./data/cms-portal.json','./ciwara-info.html','./ciwara-tv.html','./download-app.html'];
const DATA_PREFIX='/data/';
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(CORE)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});
async function enhanceHtml(response){if(!response||!response.ok)return response;try{const text=await response.text();let enhanced=text.replace(/<\\/body>/i,'');enhanced=enhanced.replace(/<script[^>]+refonte-dynamique\\.js[^>]*><\\/script>/gi,'');enhanced=enhanced.replace(/<script[^>]+refonte-dynamique-safe\\.js[^>]*><\\/script>/gi,'');enhanced=enhanced.replace(/<script[^>]+refonte-emissions\\.js[^>]*><\\/script>/gi,'');enhanced += `<script src="${SAFE_RUNTIME}" defer></script><script src="${EMISSIONS_RUNTIME}" defer></script></body>`;const headers=new Headers(response.headers);headers.set('content-type','text/html; charset=UTF-8');headers.delete('content-length');return new Response(enhanced,{status:response.status,statusText:response.statusText,headers})}catch(e){return response}}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;
if(url.pathname.startsWith(DATA_PREFIX)){event.respondWith(fetch(request).then(response=>{if(response.ok){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(request,copy))}return response}).catch(()=>caches.match(request)));return}
if(request.mode==='navigate'){event.respondWith(fetch(request).then(async response=>{const enhanced=await enhanceHtml(response);const copy=enhanced.clone();caches.open(CACHE).then(cache=>cache.put(request,copy));return enhanced}).catch(()=>caches.match('./index.html')));return}
event.respondWith(caches.match(request).then(cached=>cached||fetch(request).then(response=>{if(response.ok){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(request,copy))}return response})))
});