name: radio_ciwara_app
description: Application mobile officielle de Radio Ciwara 105.5 FM.
publish_to: "none"
version: 0.2.0+3

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.10.5
  webview_flutter: ^4.13.0
  http: ^1.5.0

flutter:
  uses-material-design: true
