name: radio_ciwara_app
description: Application mobile officielle de Radio Ciwara 105.5 FM.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.10.5
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true
