import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:http/http.dart' as http;
import 'package:just_audio/just_audio.dart';
import 'package:webview_flutter/webview_flutter.dart';

const siteBase='https://ciwara-medias.ml';
const playerUrl='$siteBase/radio-player.html';
const streamUrl='https://uk5freenew.listen2myradio.com/live.mp3?typeportmount=s1_35628_stream_416941156';
const logoUrl='$siteBase/assets/ciwara-logo-v2.svg';
const newsUrl='$siteBase/data/news.json';
const scheduleUrl='$siteBase/data/schedule.json';
const websiteUrl='$siteBase/';
const tvUrl='$siteBase/ciwara-tv.html';
const infoUrl='$siteBase/ciwara-info.html';

void main()=>runApp(const RadioCiwaraApp());
class RadioCiwaraApp extends StatelessWidget{const RadioCiwaraApp({super.key});@override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Radio Ciwara 105.5 FM',theme:ThemeData(useMaterial3:true,brightness:Brightness.dark,colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xFFD4145A),brightness:Brightness.dark)),home:const AppShell());}
class AppShell extends StatefulWidget{const AppShell({super.key});@override State<AppShell> createState()=>_AppShellState();}
class _AppShellState extends State<AppShell>{int index=0;final pages=const[DirectScreen(),ScheduleScreen(),PodcastsScreen(),NewsScreen(),MoreScreen()];@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Row(children:[SizedBox(width:44,height:44,child:SvgPicture.network(logoUrl)),const SizedBox(width:10),const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('CIWARA',style:TextStyle(fontWeight:FontWeight.w900)),Text('105.5 FM • Bamako',style:TextStyle(fontSize:11))])])),body:pages[index],bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(i)=>setState(()=>index=i),destinations:const[NavigationDestination(icon:Icon(Icons.radio_outlined),selectedIcon:Icon(Icons.radio),label:'Direct'),NavigationDestination(icon:Icon(Icons.calendar_month_outlined),selectedIcon:Icon(Icons.calendar_month),label:'Grille'),NavigationDestination(icon:Icon(Icons.podcasts_outlined),selectedIcon:Icon(Icons.podcasts),label:'Podcasts'),NavigationDestination(icon:Icon(Icons.newspaper_outlined),selectedIcon:Icon(Icons.newspaper),label:'Actus'),NavigationDestination(icon:Icon(Icons.menu),label:'Plus')]),floatingActionButton:index==0?null:FloatingActionButton.extended(onPressed:()=>setState(()=>index=0),icon:const Icon(Icons.radio),label:const Text('Direct')));}

class DirectScreen extends StatefulWidget{const DirectScreen({super.key});@override State<DirectScreen> createState()=>_DirectScreenState();}
class _DirectScreenState extends State<DirectScreen>{late final WebViewController controller;late final AudioPlayer audioPlayer;Timer? fallbackTimer;bool pageLoaded=false,casterReady=false,fallbackPlaying=false,fallbackLoading=false;String status='Connexion au lecteur officiel Caster.fm…';
@override void initState(){super.initState();audioPlayer=AudioPlayer();controller=WebViewController()..setJavaScriptMode(JavaScriptMode.unrestricted)..setBackgroundColor(const Color(0xFF120108))..addJavaScriptChannel('casterStatus',onMessageReceived:(m){if(!mounted)return;if(m.message=='ready'){fallbackTimer?.cancel();setState((){casterReady=true;status='Lecteur officiel Caster.fm connecté au site Radio Ciwara';});}else if(m.message=='failed'&&!casterReady)_activateFallback();})..setNavigationDelegate(NavigationDelegate(onPageFinished:(_){if(!mounted)return;setState(()=>pageLoaded=true);fallbackTimer?.cancel();fallbackTimer=Timer(const Duration(seconds:12),(){if(mounted&&!casterReady)_activateFallback();});},onWebResourceError:(_){if(mounted&&!casterReady)_activateFallback();}))..loadRequest(Uri.parse(playerUrl));}
void _activateFallback(){if(!mounted||casterReady||fallbackPlaying||fallbackLoading)return;setState(()=>status='Caster.fm indisponible — bascule vers le flux direct…');_playFallback(auto:true);}
Future<void> _playFallback({bool auto=false})async{if(fallbackPlaying||fallbackLoading)return;setState(()=>fallbackLoading=true);try{await audioPlayer.setUrl(streamUrl);await audioPlayer.play();if(!mounted)return;setState((){fallbackPlaying=true;fallbackLoading=false;status=auto?'Flux audio direct actif — secours Caster.fm.':'Flux audio direct actif.';});}catch(_){if(!mounted)return;setState((){fallbackLoading=false;status='Le flux direct est momentanément indisponible. Vérifiez votre connexion.';});}}
Future<void> _stopFallback()async{await audioPlayer.stop();if(!mounted)return;setState((){fallbackPlaying=false;status=casterReady?'Lecteur officiel Caster.fm connecté au site Radio Ciwara':'Lecteur Caster.fm disponible';});}
@override void dispose(){fallbackTimer?.cancel();audioPlayer.dispose();super.dispose();}
@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(18),children:[Container(padding:const EdgeInsets.all(24),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF8E0034),Color(0xFF28000F)]),borderRadius:BorderRadius.circular(28)),child:Column(children:[const Text('🔴 EN DIRECT',style:TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:18),SizedBox(width:180,height:180,child:SvgPicture.network(logoUrl)),const SizedBox(height:16),const Text('RADIO CIWARA',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const Text('105.5 FM • Bamako, Mali',style:TextStyle(fontWeight:FontWeight.w700)),const SizedBox(height:18),SizedBox(height:250,width:double.infinity,child:ClipRRect(borderRadius:BorderRadius.circular(18),child:Stack(children:[WebViewWidget(controller:controller),if(!pageLoaded&&!fallbackPlaying)const Center(child:CircularProgressIndicator())]))),const SizedBox(height:10),Text(status,textAlign:TextAlign.center,style:const TextStyle(color:Colors.white70)),const SizedBox(height:12),FilledButton.icon(onPressed:fallbackLoading?null:(fallbackPlaying?_stopFallback:_playFallback),icon:Icon(fallbackPlaying?Icons.stop:Icons.headphones),label:Text(fallbackLoading?'Connexion…':fallbackPlaying?'Arrêter le flux de secours':'Tester le flux audio direct'))])),const SizedBox(height:20),const _InfoCard(icon:Icons.volume_up,title:'Direct Radio Ciwara',text:'Même lecteur Caster.fm que le site, avec le flux audio direct en secours.'),const _InfoCard(icon:Icons.public,title:'Source connectée',text:'Application reliée aux données publiques de ciwara-medias.ml.')]);}

class ScheduleScreen extends StatelessWidget{const ScheduleScreen({super.key});@override Widget build(BuildContext context)=>FutureBuilder<String>(future:_get(scheduleUrl),builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return const _ErrorPage(title:'Grille indisponible',text:'Réessayez lorsque la connexion est disponible.');final d=jsonDecode(s.data!);final days=d['days'] is List?d['days'] as List:<dynamic>[];final provisional=d['status']=='provisional';return ListView(padding:const EdgeInsets.all(18),children:[const Text('Grille des programmes',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:6),Text(provisional?'Source provisoire.':'Programme Radio Ciwara.',style:const TextStyle(color:Colors.white70)),const SizedBox(height:18),...days.map((day){final items=day is Map&&day['items'] is List?day['items'] as List:<dynamic>[];return Card(child:ExpansionTile(title:Text(day is Map?day['day']?.toString()??'':''),children:[...items.map((item)=>ListTile(leading:const Icon(Icons.access_time),title:Text(item is Map?item['title']?.toString()??'':''),subtitle:Text(item is Map?'${item['time']?.toString()??''} • ${item['description']?.toString()??''}':'')))]));})]);});}
class NewsScreen extends StatefulWidget{const NewsScreen({super.key});@override State<NewsScreen> createState()=>_NewsScreenState();}
class _NewsScreenState extends State<NewsScreen>{late Future<String> futureNews;@override void initState(){super.initState();futureNews=_get(newsUrl);}Future<void> refresh()async{final f=_get(newsUrl);setState(()=>futureNews=f);await f;}@override Widget build(BuildContext context)=>FutureBuilder<String>(future:futureNews,builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return const _ErrorPage(title:'Actualités indisponibles',text:'Réessayez lorsque la connexion est disponible.');final d=jsonDecode(s.data!);final items=d['items'] is List?d['items'] as List:<dynamic>[];return RefreshIndicator(onRefresh:refresh,child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.all(18),children:[const Text('Actualités',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const Text('Actualités synchronisées depuis le site Radio Ciwara.',style:TextStyle(color:Colors.white70)),const SizedBox(height:16),...items.take(10).map((n)=>Card(child:ListTile(title:Text(n is Map?n['title']?.toString()??'':'',maxLines:3,overflow:TextOverflow.ellipsis),subtitle:Text(n is Map?n['source']?.toString()??'':''),trailing:const Icon(Icons.open_in_new),onTap:(){final link=n is Map?n['link']?.toString()??'':'';if(link.isNotEmpty)Navigator.of(context).push(MaterialPageRoute(builder:(_)=>WebPageScreen(title:'Actualité',url:link)));}))) ]));});}
class PodcastsScreen extends StatelessWidget{const PodcastsScreen({super.key});@override Widget build(BuildContext context)=>const _Section(title:'Podcasts',subtitle:'Espace prêt pour les vrais podcasts et replays de Radio Ciwara.',cards:[('Dernières émissions',Icons.podcasts),('Réécouter',Icons.play_circle_outline),('Archives',Icons.library_music)]);}
class MoreScreen extends StatelessWidget{const MoreScreen({super.key});@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(18),children:[const Text('Radio Ciwara',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const Text('105.5 FM • Bamako, Mali',style:TextStyle(color:Colors.white70)),const SizedBox(height:18),_MenuTile(icon:Icons.live_tv,title:'Ciwara TV',text:'Ouvrir Ciwara TV',url:tvUrl),_MenuTile(icon:Icons.article,title:'Ciwara Info',text:'Ouvrir Ciwara Info',url:infoUrl),_MenuTile(icon:Icons.language,title:'Site Web',text:'Ouvrir ciwara-medias.ml',url:websiteUrl),const _MenuTile(icon:Icons.favorite,title:'Radio Ciwara',text:'La voix qui rassemble.')]);}
class _MenuTile extends StatelessWidget{final IconData icon;final String title,text;final String? url;const _MenuTile({required this.icon,required this.title,required this.text,this.url});@override Widget build(BuildContext context)=>Card(child:ListTile(leading:Icon(icon),title:Text(title,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(text),trailing:const Icon(Icons.arrow_forward_ios,size:15),onTap:url==null?null:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>WebPageScreen(title:title,url:url!)))));}
class WebPageScreen extends StatefulWidget{final String title,url;const WebPageScreen({super.key,required this.title,required this.url});@override State<WebPageScreen> createState()=>_WebPageScreenState();}
class _WebPageScreenState extends State<WebPageScreen>{late final WebViewController controller;@override void initState(){super.initState();controller=WebViewController()..setJavaScriptMode(JavaScriptMode.unrestricted)..loadRequest(Uri.parse(widget.url));}@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(widget.title)),body:WebViewWidget(controller:controller));}
class _Section extends StatelessWidget{final String title,subtitle;final List<(String,IconData)> cards;const _Section({required this.title,required this.subtitle,required this.cards});@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(18),children:[Text(title,style:const TextStyle(fontSize:28,fontWeight:FontWeight.w900)),Text(subtitle,style:const TextStyle(color:Colors.white70)),const SizedBox(height:18),...cards.map((x)=>Card(child:ListTile(leading:Icon(x.$2),title:Text(x.$1),trailing:const Icon(Icons.arrow_forward_ios,size:15))))]);}
class _InfoCard extends StatelessWidget{final IconData icon;final String title,text;const _InfoCard({required this.icon,required this.title,required this.text});@override Widget build(BuildContext context)=>Card(child:ListTile(leading:Icon(icon),title:Text(title,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(text)));}
class _ErrorPage extends StatelessWidget{final String title,text;const _ErrorPage({required this.title,required this.text});@override Widget build(BuildContext context)=>Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.wifi_off,size:50),const SizedBox(height:12),Text(title,style:const TextStyle(fontSize:22,fontWeight:FontWeight.w800)),const SizedBox(height:8),Text(text,textAlign:TextAlign.center)])));}
Future<String> _get(String url)async{final r=await http.get(Uri.parse(url),headers:{'Cache-Control':'no-cache'});if(r.statusCode!=200)throw Exception('HTTP ${r.statusCode}');return r.body;}
