import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:just_audio/just_audio.dart';
import 'package:webview_flutter/webview_flutter.dart';

const casterPublicToken='236f6884-9ad2-465f-a29e-5f349a8dac8e';
const streamUrl='https://uk5freenew.listen2myradio.com/live.mp3?typeportmount=s1_35628_stream_416941156';
const siteBase='https://raw.githubusercontent.com/cmbenkouma-alt/Radio-Ciwara-/app-foundation/';
const logoUrl='${siteBase}logo.jpg';
const newsUrl='${siteBase}data/news.json';
const scheduleUrl='${siteBase}data/schedule.json';
const websiteUrl='https://ciwara-medias.ml/';
const tvUrl='https://ciwara-medias.ml/ciwara-tv.html';
const infoUrl='https://ciwara-medias.ml/ciwara-info.html';

void main()=>runApp(const RadioCiwaraApp());

class RadioCiwaraApp extends StatelessWidget{const RadioCiwaraApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Radio Ciwara 105.5 FM',theme:ThemeData(useMaterial3:true,brightness:Brightness.dark,colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xFFD4145A),brightness:Brightness.dark)),home:const AppShell());}
class AppShell extends StatefulWidget{const AppShell({super.key});@override State<AppShell> createState()=>_AppShellState();}
class _AppShellState extends State<AppShell>{int index=0;final pages=const[DirectScreen(),ScheduleScreen(),PodcastsScreen(),NewsScreen(),MoreScreen()];@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Row(children:[ClipOval(child:Image.network(logoUrl,width:42,height:42,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Icon(Icons.radio))),const SizedBox(width:10),const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('CIWARA',style:TextStyle(fontWeight:FontWeight.w900)),Text('105.5 FM • Bamako',style:TextStyle(fontSize:11))])])),body:pages[index],bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(i)=>setState(()=>index=i),destinations:const[NavigationDestination(icon:Icon(Icons.radio_outlined),selectedIcon:Icon(Icons.radio),label:'Direct'),NavigationDestination(icon:Icon(Icons.calendar_month_outlined),selectedIcon:Icon(Icons.calendar_month),label:'Grille'),NavigationDestination(icon:Icon(Icons.podcasts_outlined),selectedIcon:Icon(Icons.podcasts),label:'Podcasts'),NavigationDestination(icon:Icon(Icons.newspaper_outlined),selectedIcon:Icon(Icons.newspaper),label:'Actus'),NavigationDestination(icon:Icon(Icons.menu),label:'Plus')]),floatingActionButton:index==0?null:FloatingActionButton.extended(onPressed:()=>setState(()=>index=0),icon:const Icon(Icons.radio),label:const Text('Direct')));}

class DirectScreen extends StatefulWidget{const DirectScreen({super.key});@override State<DirectScreen> createState()=>_DirectScreenState();}
class _DirectScreenState extends State<DirectScreen>{late final WebViewController controller;late final AudioPlayer audio;Timer? timer;bool pageLoaded=false,casterReady=false,fallback=false,loading=false;String status='Chargement du lecteur officiel Caster.fm…';
@override void initState(){super.initState();audio=AudioPlayer();controller=WebViewController()..setJavaScriptMode(JavaScriptMode.unrestricted)..setBackgroundColor(const Color(0xFF120108))..addJavaScriptChannel('casterStatus',onMessageReceived:(m){if(!mounted)return;if(m.message=='ready'){timer?.cancel();setState((){casterReady=true;status='Lecteur officiel Caster.fm prêt';});}else if(m.message=='failed'&&!casterReady){_fallback();}})..setNavigationDelegate(NavigationDelegate(onPageFinished:(_){if(!mounted)return;setState(()=>pageLoaded=true);controller.runJavaScript('''(function(){let n=0;let t=setInterval(function(){n++;let e=document.querySelector('.cstrEmbed');let p=e&&e.querySelector('iframe,audio,button,[role="button"],input');if(p){casterStatus.postMessage('ready');clearInterval(t);}if(n>=20){casterStatus.postMessage('failed');clearInterval(t);}},500);})();''');timer?.cancel();timer=Timer(const Duration(seconds:12),(){if(mounted&&!casterReady)_fallback();});},onWebResourceError:(_){if(mounted&&!casterReady)_fallback();}))..loadHtmlString(_casterHtml,baseUrl:'https://www.caster.fm/');}
void _fallback(){if(!mounted||fallback||loading)return;setState(()=>status='Caster.fm indisponible — utilisation du flux audio direct…');_playFallback(auto:true);}
Future<void> _playFallback({bool auto=false})async{if(fallback||loading)return;setState(()=>loading=true);try{await audio.setUrl(streamUrl);await audio.play();if(mounted)setState((){fallback=true;loading=false;status=auto?'Flux audio direct actif (secours).':'Flux audio direct actif.';});}catch(_){if(mounted){setState((){loading=false;status='Le flux audio est momentanément indisponible.';});}}}
Future<void> _stopFallback()async{await audio.stop();if(mounted)setState((){fallback=false;status=casterReady?'Lecteur officiel Caster.fm prêt':'Lecteur Caster.fm disponible';});}
@override void dispose(){timer?.cancel();audio.dispose();super.dispose();}
@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(18),children:[Container(padding:const EdgeInsets.all(24),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF8E0034),Color(0xFF28000F)]),borderRadius:BorderRadius.circular(28)),child:Column(children:[const Text('🔴 EN DIRECT',style:TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:18),ClipOval(child:Image.network(logoUrl,width:150,height:150,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Icon(Icons.radio,size:100))),const SizedBox(height:16),const Text('RADIO CIWARA',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const Text('105.5 FM • Bamako, Mali',style:TextStyle(fontWeight:FontWeight.w700)),const SizedBox(height:18),SizedBox(height:250,width:double.infinity,child:ClipRRect(borderRadius:BorderRadius.circular(18),child:Stack(children:[WebViewWidget(controller:controller),if(!pageLoaded&&!fallback)const Center(child:CircularProgressIndicator())]))),const SizedBox(height:10),Text(status,textAlign:TextAlign.center,style:const TextStyle(color:Colors.white70)),const SizedBox(height:12),if(!casterReady||fallback)FilledButton.icon(onPressed:loading?null:(fallback?_stopFallback:_playFallback),icon:Icon(fallback?Icons.stop:Icons.headphones),label:Text(loading?'Connexion…':fallback?'Arrêter le flux de secours':'Utiliser le flux audio direct'))])),const SizedBox(height:20),const _InfoCard(icon:Icons.volume_up,title:'Direct Radio Ciwara',text:'Caster.fm officiel avec bascule automatique vers le flux audio direct.'),const _InfoCard(icon:Icons.public,title:'Radio Ciwara 105.5 FM',text:'La voix qui rassemble.')]);}
const _casterHtml='''<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>html,body{margin:0;background:#120108;color:#fff;font-family:Arial;overflow:hidden}.cstrEmbed{width:100%;min-height:230px}a{color:#fff}</style></head><body><div class="cstrEmbed" data-type="newStreamPlayer" data-publicToken="$casterPublicToken" data-theme="light" data-color="D4145A" data-channelId="" data-rendered="false"><a href="https://www.caster.fm">Radio Server Hosting</a></div><script src="https://cdn.cloud.caster.fm/widgets/embed.js"></script></body></html>''';

class ScheduleScreen extends StatelessWidget{const ScheduleScreen({super.key});@override Widget build(BuildContext c)=>FutureBuilder<String>(future:_get(scheduleUrl),builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return const _ErrorPage(title:'Grille indisponible',text:'Réessayez lorsque la connexion est disponible.');final d=jsonDecode(s.data!);final days=(d['days'] as List? ?? []);return ListView(padding:const EdgeInsets.all(18),children:[const Text('Grille des programmes',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const Text('Horaires Radio Ciwara',style:TextStyle(color:Colors.white70)),const SizedBox(height:18),...days.map((day){final items=(day['items'] as List? ?? []);return Card(child:ExpansionTile(title:Text(day['day']?.toString()??''),children:[...items.map((p)=>ListTile(leading:const Icon(Icons.access_time),title:Text(p['title']?.toString()??''),subtitle:Text('${p['time']?.toString()??''} • ${p['description']?.toString()??''}')))]));})]);});}
class NewsScreen extends StatefulWidget{const NewsScreen({super.key});@override State<NewsScreen> createState()=>_NewsScreenState();}
class _NewsScreenState extends State<NewsScreen>{late Future<String> future;@override void initState(){super.initState();future=_get(newsUrl);}Future<void> refresh()async{final f=_get(newsUrl);setState(()=>future=f);await f;}@override Widget build(BuildContext c)=>FutureBuilder<String>(future:future,builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return const _ErrorPage(title:'Actualités indisponibles',text:'Réessayez lorsque la connexion est disponible.');final d=jsonDecode(s.data!);final items=(d['items'] as List? ?? []);return RefreshIndicator(onRefresh:refresh,child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.all(18),children:[const Text('Actualités',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const Text('Sources : Maliweb et Malijet',style:TextStyle(color:Colors.white70)),const SizedBox(height:16),...items.take(10).map((n)=>Card(child:ListTile(title:Text(n['title']?.toString()??'',maxLines:3,overflow:TextOverflow.ellipsis),subtitle:Text(n['source']?.toString()??''),trailing:const Icon(Icons.open_in_new),onTap:(){final u=n['link']?.toString()??'';if(u.isNotEmpty)Navigator.of(c).push(MaterialPageRoute(builder:(_)=>WebPageScreen(title:'Actualité',url:u)));}))) ]));});}
class PodcastsScreen extends StatelessWidget{const PodcastsScreen({super.key});@override Widget build(BuildContext c)=>const _Section(title:'Podcasts',subtitle:'Espace prêt pour les vrais podcasts et replays de Radio Ciwara.',cards:[('Dernières émissions',Icons.podcasts),('Réécouter',Icons.play_circle_outline),('Archives',Icons.library_music)]);}
class MoreScreen extends StatelessWidget{const MoreScreen({super.key});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(18),children:[const Text('Radio Ciwara',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const Text('105.5 FM • Bamako, Mali',style:TextStyle(color:Colors.white70)),const SizedBox(height:18),_MenuTile(icon:Icons.live_tv,title:'Ciwara TV',text:'Ouvrir Ciwara TV',url:tvUrl),_MenuTile(icon:Icons.article,title:'Ciwara Info',text:'Ouvrir Ciwara Info',url:infoUrl),_MenuTile(icon:Icons.language,title:'Site Web',text:'Radio Ciwara en ligne',url:websiteUrl)]);}
class _MenuTile extends StatelessWidget{final IconData icon;final String title,text;final String? url;const _MenuTile({required this.icon,required this.title,required this.text,this.url});@override Widget build(BuildContext c)=>Card(child:ListTile(leading:Icon(icon),title:Text(title,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(text),trailing:const Icon(Icons.arrow_forward_ios,size:15),onTap:url==null?null:()=>Navigator.of(c).push(MaterialPageRoute(builder:(_)=>WebPageScreen(title:title,url:url!)))));}
class WebPageScreen extends StatefulWidget{final String title,url;const WebPageScreen({super.key,required this.title,required this.url});@override State<WebPageScreen> createState()=>_WebPageScreenState();}
class _WebPageScreenState extends State<WebPageScreen>{late final WebViewController controller;@override void initState(){super.initState();controller=WebViewController()..setJavaScriptMode(JavaScriptMode.unrestricted)..loadRequest(Uri.parse(widget.url));}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(widget.title)),body:WebViewWidget(controller:controller));}
class _Section extends StatelessWidget{final String title,subtitle;final List<(String,IconData)> cards;const _Section({required this.title,required this.subtitle,required this.cards});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(18),children:[Text(title,style:const TextStyle(fontSize:28,fontWeight:FontWeight.w900)),Text(subtitle,style:const TextStyle(color:Colors.white70)),const SizedBox(height:18),...cards.map((x)=>Card(child:ListTile(leading:Icon(x.$2),title:Text(x.$1),trailing:const Icon(Icons.arrow_forward_ios,size:15))))]);}
class _InfoCard extends StatelessWidget{final IconData icon;final String title,text;const _InfoCard({required this.icon,required this.title,required this.text});@override Widget build(BuildContext c)=>Card(child:ListTile(leading:Icon(icon),title:Text(title,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(text)));}
class _ErrorPage extends StatelessWidget{final String title,text;const _ErrorPage({required this.title,required this.text});@override Widget build(BuildContext c)=>Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.wifi_off,size:50),const SizedBox(height:12),Text(title,style:const TextStyle(fontSize:22,fontWeight:FontWeight.w800)),const SizedBox(height:8),Text(text,textAlign:TextAlign.center)])));}
Future<String> _get(String url)async{final r=await http.get(Uri.parse(url));if(r.statusCode!=200)throw Exception('HTTP ${r.statusCode}');return r.body;}
